spring:
  application:
    name: inventory
  data:
    mongodb:
      uri: mongodb://localhost:27017/local
  main:
    application-startup: buffering

management:
  endpoints:
    web:
      exposure:
        include: startup
logging:
  level:
    root: INFO
  com.example.inventory: DEBUG