spring:
  application:
    name: inventory
  data:
    mongodb:
      uri: mongodb://localhost:27017/local

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO
  com.example.inventory: DEBUG